/**
 * @swagger
 * components:
 *   schemas:
 *     Product:
 *       type: object
 *       properties:
 *         id:
 *           type: integer
 *           description: Autogenerated product ID.
 *           example: 1
 *           readOnly: true
 *         name:
 *           type: string
 *           description: Product name.
 *           example: 'Laptop XYZ'
 *         description:
 *           type: string
 *           description: Product description.
 *           example: 'A powerful laptop for developers.'
 *         price:
 *           type: string
 *           description: Product price.
 *           example: '1500.00'
 *         stock:
 *           type: integer
 *           description: Stock quantity.
 *           example: 50
 *         categoryId:
 *           type: integer
 *           description: ID of the category it belongs to.
 *           example: 1
 *         brandId:
 *           type: integer
 *           description: ID of the brand it belongs to.
 *           example: 1
 *       required:
 *         - name
 *         - description
 *         - price
 *         - stock
 *         - categoryId
 *         - brandId
 *
 *     ProductUpdate:
 *       type: object
 *       description: Optional fields to update a product.
 *       properties:
 *         name:
 *           type: string
 *           example: 'Laptop XYZ v2'
 *         description:
 *           type: string
 *           example: 'Updated version of the laptop.'
 *         price:
 *           type: string
 *           example: '1550.00'
 *         stock:
 *           type: integer
 *           example: 45
 *         categoryId:
 *           type: integer
 *           example: 1
 *         brandId:
 *           type: integer
 *           example: 1
 *
 *     User:
 *       type: object
 *       properties:
 *         id:
 *           type: integer
 *           example: 1
 *           readOnly: true
 *         name:
 *           type: string
 *           example: 'John Doe'
 *         username:
 *           type: string
 *           example: 'johndoe'
 *         password:
 *           type: string
 *           description: Password (in a real case, this should not be exposed).
 *           example: 'password123'
 *       required:
 *         - name
 *         - username
 *         - password
 *
 *     UserUpdate:
 *       type: object
 *       description: Optional fields to update a user.
 *       properties:
 *         name:
 *           type: string
 *           example: 'John A. Doe'
 *         username:
 *           type: string
 *           example: 'johndoe88'
 *         password:
 *           type: string
 *           example: 'newPassword456'
 *
 *     Category:
 *       type: object
 *       properties:
 *         id:
 *           type: integer
 *           example: 1
 *           readOnly: true
 *         name:
 *           type: string
 *           example: 'Electronics'
 *         description:
 *           type: string
 *           example: 'Electronic devices and accessories.'
 *         active:
 *           type: boolean
 *           example: true
 *       required:
 *         - name
 *         - description
 *         - active
 *
 *     CategoryUpdate:
 *       type: object
 *       description: Optional fields to update a category.
 *       properties:
 *         name:
 *           type: string
 *         description:
 *           type: string
 *         active:
 *           type: boolean
 *
 *     Brand:
 *       type: object
 *       properties:
 *         id:
 *           type: integer
 *           example: 1
 *           readOnly: true
 *         name:
 *           type: string
 *           example: 'ACME Brand'
 *         description:
 *           type: string
 *           example: 'Manufacturer of high-quality products.'
 *         active:
 *           type: boolean
 *           example: true
 *       required:
 *         - name
 *         - description
 *         - active
 *
 *     BrandUpdate:
 *       type: object
 *       description: Optional fields to update a brand.
 *       properties:
 *         name:
 *           type: string
 *         description:
 *           type: string
 *         active:
 *           type: boolean
 *
 *     Error:
 *       type: object
 *       properties:
 *         status:
 *           type: string
 *           example: 'fail'
 *         message:
 *           type: string
 *           example: 'Resource not found'
 *
 *   # PARAMETERS
 *   parameters:
 *     idParam:
 *       in: path
 *       name: id
 *       schema:
 *         type: integer
 *       required: true
 *       description: Numeric ID of the resource.
 *       example: 1
 *     categoryIdParam:
 *       in: path
 *       name: categoryId
 *       schema:
 *         type: integer
 *       required: true
 *       description: Numeric ID of the category.
 *       example: 1
 *     brandIdParam:
 *       in: path
 *       name: brandId
 *       schema:
 *         type: integer
 *       required: true
 *       description: Numeric ID of the brand.
 *       example: 1
 *
 *   # RESPONSES
 *   responses:
 *     SuccessDelete:
 *       description: Resource deleted successfully.
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               message:
 *                 type: string
 *                 example: 'Resource deleted'
 *     NotFound:
 *       description: The requested resource was not found.
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Error'
 *           example:
 *             status: 'fail'
 *             message: 'Resource not found'
 *     BadRequest:
 *       description: Invalid input data or missing fields.
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Error'
 *           example:
 *             status: 'fail'
 *             message: 'Missing fields'
 *     Conflict:
 *       description: Conflict, the resource is in use.
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Error'
 *           example:
 *             status: 'fail'
 *             message: 'Resource is in use and cannot be deleted'
 *
 *   # REQUEST BODIES
 *   requestBodies:
 *     ProductBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Product'
 *     ProductUpdateBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/ProductUpdate'
 *     UserBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/User'
 *     UserUpdateBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/UserUpdate'
 *     CategoryBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Category'
 *     CategoryUpdateBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/CategoryUpdate'
 *     BrandBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Brand'
 *     BrandUpdateBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/BrandUpdate'
 */
